# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\toolloader.ui'
#
# Created: Mon Aug 08 19:25:24 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(761, 561)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/control-center2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.toolTreeWidget = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolTreeWidget.sizePolicy().hasHeightForWidth())
        self.toolTreeWidget.setSizePolicy(sizePolicy)
        self.toolTreeWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.toolTreeWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.toolTreeWidget.setObjectName(_fromUtf8("toolTreeWidget"))
        self.horizontalLayout_2.addWidget(self.toolTreeWidget)
        self.helpTextEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpTextEdit.sizePolicy().hasHeightForWidth())
        self.helpTextEdit.setSizePolicy(sizePolicy)
        self.helpTextEdit.setMinimumSize(QtCore.QSize(0, 150))
        self.helpTextEdit.setMaximumSize(QtCore.QSize(16777215, 150))
        self.helpTextEdit.setObjectName(_fromUtf8("helpTextEdit"))
        self.horizontalLayout_2.addWidget(self.helpTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.extentLabel = QtGui.QLabel(self.centralwidget)
        self.extentLabel.setObjectName(_fromUtf8("extentLabel"))
        self.verticalLayout.addWidget(self.extentLabel)
        self.outputTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.verticalLayout.addWidget(self.outputTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuBackend = QtGui.QMenu(self.menuSettings)
        self.menuBackend.setObjectName(_fromUtf8("menuBackend"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionArcGIS = QtGui.QAction(MainWindow)
        self.actionArcGIS.setCheckable(True)
        self.actionArcGIS.setChecked(True)
        self.actionArcGIS.setObjectName(_fromUtf8("actionArcGIS"))
        self.actionOSGeo = QtGui.QAction(MainWindow)
        self.actionOSGeo.setEnabled(False)
        self.actionOSGeo.setObjectName(_fromUtf8("actionOSGeo"))
        self.action = QtGui.QAction(MainWindow)
        self.action.setText(_fromUtf8(""))
        self.action.setObjectName(_fromUtf8("action"))
        self.actionLoad_tool = QtGui.QAction(MainWindow)
        self.actionLoad_tool.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/document-open.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_tool.setIcon(icon1)
        self.actionLoad_tool.setObjectName(_fromUtf8("actionLoad_tool"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/system-shutdown.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/help-contents.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon3)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionDebugging_messages = QtGui.QAction(MainWindow)
        self.actionDebugging_messages.setCheckable(True)
        self.actionDebugging_messages.setChecked(False)
        self.actionDebugging_messages.setObjectName(_fromUtf8("actionDebugging_messages"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gtk-info.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpen_log = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/kfind.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_log.setIcon(icon5)
        self.actionOpen_log.setObjectName(_fromUtf8("actionOpen_log"))
        self.menuBackend.addAction(self.actionArcGIS)
        self.menuBackend.addAction(self.actionOSGeo)
        self.menuSettings.addAction(self.menuBackend.menuAction())
        self.menuFile.addAction(self.actionLoad_tool)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionOpen_log)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuView.addAction(self.actionDebugging_messages)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionLoad_tool)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionOpen_log)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Available plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.extentLabel.setText(QtGui.QApplication.translate("MainWindow", "Current extent: Not set", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBackend.setTitle(QtGui.QApplication.translate("MainWindow", "Backend", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArcGIS.setText(QtGui.QApplication.translate("MainWindow", "ArcGIS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOSGeo.setText(QtGui.QApplication.translate("MainWindow", "OSGeo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_tool.setText(QtGui.QApplication.translate("MainWindow", "&Load tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_tool.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebugging_messages.setText(QtGui.QApplication.translate("MainWindow", "&Debugging messages", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_log.setText(QtGui.QApplication.translate("MainWindow", "O&pen log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_log.setToolTip(QtGui.QApplication.translate("MainWindow", "Open the log file", None, QtGui.QApplication.UnicodeUTF8))

import toolloader_rc
